- name: install logstash (Ubuntu)
  apt:
    name: logstash
    state: present
  when: ansible_distribution == "Ubuntu"

- name: install logstash (CentOS)
  yum:
    name: logstash
    state: present
  when: ansible_distribution == "CentOS"

- name: logstash restarting / enabling
  systemd:
    name: logstash
    enabled: true
    state: started
  become: yes
