- name: install the prerequisite
  apt:
    name:
      - gnupg2
      - curl
      - software-properties-common
  when: ansible_distribution == "Ubuntu"

- name: Add Grafana APT GPG key
  apt_key:
    url: https://packages.grafana.com/gpg.key
    state: present
  when: ansible_distribution == "Ubuntu"

- name: add grafana repository
  apt_repository:
    repo: "deb https://packages.grafana.com/oss/deb stable main"
    state: present
  when: ansible_distribution == "Ubuntu"

- name: add grafana gpg key
  get_url:
    url: https://packages.grafana.com/gpg.key
    state: present
  when: ansible_distribution == "CentOS"

- name: add grafana repository
  yum_repository:
    url: https://packages.grafana.com/oss/rpm
    enabled: yes
  when: ansible_distribution == "CentOS"

- name: install grafana
  package:
    name: grafana
    state: present

- name: grafana restarting / enabling
  service:
    name: grafana-server
    state: started
    enabled: yes

